services:
  backend:
    volumes:
      - ./backend:/app
      - /app/venv  # Exclude venv directory
    environment:
      - PYTHONUNBUFFERED=1
      - RELOAD=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8005", "--reload"]

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules
      - /app/.next         # Exclude .next build directory
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"] 